import React, { useState, useContext } from "react";
import TableView from "../viewTypes/tableview";
import { DataContext } from '../context_provider/Datafetcher';

//operation to search by cluster id

function Cluster(){
const [name, setName] = useState('');
const [organismdata, setOrganismdata] = useState([]);
const [isButtonClicked, setIsButtonClicked] = useState(false);

const handleInputChange = (event) => {
  setIsButtonClicked(false);
  setName(event.target.value);
};

const handleFormSubmit = async (event) => {
  event.preventDefault();
  try {
    const response = await fetch(`/api/querypage_calls/cluster_id?id=${name}`);
    const data = await response.json();
    console.log("gene name data:", data, data.data);
    setOrganismdata(data.data);
    setIsButtonClicked(true); // Set the flag indicating that the button is clicked

  } catch (error) {
    console.error(error);
  }
};

return (

<div>
  <h2> Search for cluster ID/Group ID </h2>
  <label htmlFor="clusterId">Enter cluster ID:</label>

  <form onSubmit={handleFormSubmit}>
        <input type="text" value={name} onChange={handleInputChange} />
        <button type="submit">Submit</button>
      </form>
<br></br>

    {isButtonClicked ? (
  organismdata !== undefined ? (
    organismdata.length > 0 ? (
      <TableView data={organismdata} />
    ) : (
      <p>Data not available. Probably an invalid gene ID was entered</p>
    )
  ) : (
    <p>Enter a valid gene ID.</p>
  )
) : null}
 Input: Cluster Id/Group ID. e.g: 179<p>
The cluster or the group ids are the group IDs generated by the clustering algorithm. 
We used OrthoMCL for clustering the protein sequences of 12 representative members e.g; Albugo laibachii Nc14, Phytophthora sojae (V5.0), Phytophthora ramorum Pr102, Phytophthora infestans T30-4, Phytophthora capsici LT1534, Phytophthora parasitica INRA-310, Hyalopernospora arabidopsidis Emoy2, Plasmopara halstedii, Pythium vexans DAOMBR484, Pythium ultimum DAOMBR144 (V1), Saprolegnia parasitica CBS223.65 (V1), Aphanomyces invadans. Conventionally the group with the largest number of proteins is Group 1 and the numbers of members are sorted in descending order.
    </p> 
    

    </div>
    )}

export default Cluster;