import '@/styles/globals.css'
import Navbar from './navbar'
import Head from 'next/head'
//import 'antd/dist/antd.css';
import 'antd/dist/reset.css';
import { DataProvider } from './components/context_provider/Datafetcher';
import { SelectedValuesProvider } from './components/context_provider/selectedvaluescontext';

function MyApp({ Component, pageProps }) {
  return <>
        <Head>
        <title>galEupy web application </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/CGLabLogo.jpg" />
        <link
          rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
          integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7"
          crossOrigin="anonymous"
        />
      </Head>
      <DataProvider>
      <SelectedValuesProvider>

  <Navbar />
  <Component {...pageProps} />
  </SelectedValuesProvider>
  </DataProvider> 
  <footer className="footer">
        <a
          href="https://sites.google.com/view/stlab-iicb/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Maintained by{' '}
          <img src="/CGLabLogo.jpg" alt="Vercel" className="logo"/>
          CG-Lab, CSIR-IICB
        </a>
      </footer>

  </>
}

export default MyApp
